// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kla.proto

package com_grpc_proto_v0

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateSessionDetailRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Talk                 string   `protobuf:"bytes,2,opt,name=talk,proto3" json:"talk,omitempty"`
	Abstract             string   `protobuf:"bytes,3,opt,name=abstract,proto3" json:"abstract,omitempty"`
	TalkTime             int64    `protobuf:"varint,4,opt,name=talkTime,proto3" json:"talkTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSessionDetailRequest) Reset()         { *m = CreateSessionDetailRequest{} }
func (m *CreateSessionDetailRequest) String() string { return proto.CompactTextString(m) }
func (*CreateSessionDetailRequest) ProtoMessage()    {}
func (*CreateSessionDetailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c8adffb6e727198, []int{0}
}

func (m *CreateSessionDetailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSessionDetailRequest.Unmarshal(m, b)
}
func (m *CreateSessionDetailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSessionDetailRequest.Marshal(b, m, deterministic)
}
func (m *CreateSessionDetailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSessionDetailRequest.Merge(m, src)
}
func (m *CreateSessionDetailRequest) XXX_Size() int {
	return xxx_messageInfo_CreateSessionDetailRequest.Size(m)
}
func (m *CreateSessionDetailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSessionDetailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSessionDetailRequest proto.InternalMessageInfo

func (m *CreateSessionDetailRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateSessionDetailRequest) GetTalk() string {
	if m != nil {
		return m.Talk
	}
	return ""
}

func (m *CreateSessionDetailRequest) GetAbstract() string {
	if m != nil {
		return m.Abstract
	}
	return ""
}

func (m *CreateSessionDetailRequest) GetTalkTime() int64 {
	if m != nil {
		return m.TalkTime
	}
	return 0
}

type CreateSessionDetailResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSessionDetailResponse) Reset()         { *m = CreateSessionDetailResponse{} }
func (m *CreateSessionDetailResponse) String() string { return proto.CompactTextString(m) }
func (*CreateSessionDetailResponse) ProtoMessage()    {}
func (*CreateSessionDetailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c8adffb6e727198, []int{1}
}

func (m *CreateSessionDetailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSessionDetailResponse.Unmarshal(m, b)
}
func (m *CreateSessionDetailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSessionDetailResponse.Marshal(b, m, deterministic)
}
func (m *CreateSessionDetailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSessionDetailResponse.Merge(m, src)
}
func (m *CreateSessionDetailResponse) XXX_Size() int {
	return xxx_messageInfo_CreateSessionDetailResponse.Size(m)
}
func (m *CreateSessionDetailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSessionDetailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSessionDetailResponse proto.InternalMessageInfo

type GetSessionDetailsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSessionDetailsRequest) Reset()         { *m = GetSessionDetailsRequest{} }
func (m *GetSessionDetailsRequest) String() string { return proto.CompactTextString(m) }
func (*GetSessionDetailsRequest) ProtoMessage()    {}
func (*GetSessionDetailsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c8adffb6e727198, []int{2}
}

func (m *GetSessionDetailsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSessionDetailsRequest.Unmarshal(m, b)
}
func (m *GetSessionDetailsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSessionDetailsRequest.Marshal(b, m, deterministic)
}
func (m *GetSessionDetailsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSessionDetailsRequest.Merge(m, src)
}
func (m *GetSessionDetailsRequest) XXX_Size() int {
	return xxx_messageInfo_GetSessionDetailsRequest.Size(m)
}
func (m *GetSessionDetailsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSessionDetailsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSessionDetailsRequest proto.InternalMessageInfo

type GetSessionDetailsResponse struct {
	CreateSessionDetailRequest []*CreateSessionDetailRequest `protobuf:"bytes,1,rep,name=createSessionDetailRequest,proto3" json:"createSessionDetailRequest,omitempty"`
	XXX_NoUnkeyedLiteral       struct{}                      `json:"-"`
	XXX_unrecognized           []byte                        `json:"-"`
	XXX_sizecache              int32                         `json:"-"`
}

func (m *GetSessionDetailsResponse) Reset()         { *m = GetSessionDetailsResponse{} }
func (m *GetSessionDetailsResponse) String() string { return proto.CompactTextString(m) }
func (*GetSessionDetailsResponse) ProtoMessage()    {}
func (*GetSessionDetailsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c8adffb6e727198, []int{3}
}

func (m *GetSessionDetailsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSessionDetailsResponse.Unmarshal(m, b)
}
func (m *GetSessionDetailsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSessionDetailsResponse.Marshal(b, m, deterministic)
}
func (m *GetSessionDetailsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSessionDetailsResponse.Merge(m, src)
}
func (m *GetSessionDetailsResponse) XXX_Size() int {
	return xxx_messageInfo_GetSessionDetailsResponse.Size(m)
}
func (m *GetSessionDetailsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSessionDetailsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSessionDetailsResponse proto.InternalMessageInfo

func (m *GetSessionDetailsResponse) GetCreateSessionDetailRequest() []*CreateSessionDetailRequest {
	if m != nil {
		return m.CreateSessionDetailRequest
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateSessionDetailRequest)(nil), "com.grpc.proto.v0.CreateSessionDetailRequest")
	proto.RegisterType((*CreateSessionDetailResponse)(nil), "com.grpc.proto.v0.CreateSessionDetailResponse")
	proto.RegisterType((*GetSessionDetailsRequest)(nil), "com.grpc.proto.v0.GetSessionDetailsRequest")
	proto.RegisterType((*GetSessionDetailsResponse)(nil), "com.grpc.proto.v0.GetSessionDetailsResponse")
}

func init() { proto.RegisterFile("kla.proto", fileDescriptor_7c8adffb6e727198) }

var fileDescriptor_7c8adffb6e727198 = []byte{
	// 321 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x52, 0xcd, 0x4e, 0x02, 0x31,
	0x10, 0x4e, 0x81, 0x18, 0x18, 0x4f, 0xd4, 0xc4, 0xd4, 0x12, 0x13, 0xb2, 0xf1, 0xb0, 0x17, 0x0b,
	0xc1, 0x27, 0x00, 0x35, 0xc6, 0xc0, 0xc1, 0x2c, 0x1e, 0xbd, 0x94, 0x65, 0x24, 0x2b, 0xdb, 0xed,
	0xba, 0x2d, 0x44, 0x13, 0x9f, 0xc0, 0x47, 0xf4, 0x69, 0x4c, 0xbb, 0x48, 0xa2, 0x80, 0x91, 0x83,
	0xb7, 0xce, 0xf7, 0xcd, 0xdf, 0x37, 0x5f, 0xa1, 0x31, 0x4f, 0xa5, 0xc8, 0x0b, 0x6d, 0x35, 0x6d,
	0xc6, 0x5a, 0x89, 0x59, 0x91, 0xc7, 0x65, 0x2c, 0x96, 0x5d, 0xde, 0x9a, 0x69, 0x3d, 0x4b, 0xb1,
	0xe3, 0x81, 0xc9, 0xe2, 0xb1, 0x83, 0x2a, 0xb7, 0xaf, 0x25, 0x1f, 0xbc, 0x01, 0xbf, 0x2c, 0x50,
	0x5a, 0x1c, 0xa3, 0x31, 0x89, 0xce, 0xae, 0xd0, 0xca, 0x24, 0x8d, 0xf0, 0x79, 0x81, 0xc6, 0x52,
	0x0a, 0xb5, 0x4c, 0x2a, 0x64, 0xa4, 0x4d, 0xc2, 0x46, 0xe4, 0xdf, 0x0e, 0xb3, 0x32, 0x9d, 0xb3,
	0x4a, 0x89, 0xb9, 0x37, 0xe5, 0x50, 0x97, 0x13, 0x63, 0x0b, 0x19, 0x5b, 0x56, 0xf5, 0xf8, 0x3a,
	0x76, 0x9c, 0xcb, 0xb9, 0x4f, 0x14, 0xb2, 0x5a, 0x9b, 0x84, 0xd5, 0x68, 0x1d, 0x07, 0xa7, 0xd0,
	0xda, 0x3a, 0xdd, 0xe4, 0x3a, 0x33, 0x18, 0x70, 0x60, 0x37, 0x68, 0xbf, 0x71, 0x66, 0xb5, 0x5a,
	0xf0, 0x4e, 0xe0, 0x64, 0x0b, 0x59, 0x56, 0x52, 0x05, 0x3c, 0xde, 0x29, 0x8b, 0x91, 0x76, 0x35,
	0x3c, 0xec, 0x9d, 0x8b, 0x8d, 0x5b, 0x89, 0xdd, 0xb7, 0x88, 0x7e, 0x69, 0xd8, 0xfb, 0xa8, 0x00,
	0x0c, 0x47, 0xfd, 0x31, 0x16, 0xcb, 0x24, 0x46, 0x6a, 0xe1, 0x68, 0x4b, 0x23, 0xba, 0xdf, 0x40,
	0x2e, 0xfe, 0x9a, 0xbe, 0xd2, 0xfc, 0x00, 0xcd, 0x8d, 0x83, 0xd0, 0x63, 0x51, 0xba, 0x2f, 0xbe,
	0xdc, 0x17, 0xd7, 0xce, 0x7d, 0xbe, 0xdf, 0x2e, 0x5d, 0x42, 0x5f, 0x7e, 0x68, 0xba, 0xcd, 0x06,
	0x8b, 0x74, 0xfe, 0xcf, 0x9a, 0x42, 0xd2, 0x25, 0x83, 0x33, 0x60, 0xae, 0xc8, 0xfd, 0xf1, 0x29,
	0x2a, 0x2d, 0x9e, 0xe4, 0x52, 0x8a, 0xa9, 0xaf, 0x1d, 0xd4, 0x87, 0xa3, 0xfe, 0x9d, 0x57, 0x76,
	0xe0, 0xfb, 0x5d, 0x7c, 0x06, 0x00, 0x00, 0xff, 0xff, 0xc6, 0xb9, 0x42, 0x96, 0x0c, 0x03, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// KLAServiceClient is the client API for KLAService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type KLAServiceClient interface {
	CreateSessionDetail(ctx context.Context, in *CreateSessionDetailRequest, opts ...grpc.CallOption) (*CreateSessionDetailResponse, error)
	GetSessionDetails(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (KLAService_GetSessionDetailsClient, error)
	CreateSessionInBulk(ctx context.Context, opts ...grpc.CallOption) (KLAService_CreateSessionInBulkClient, error)
}

type kLAServiceClient struct {
	cc *grpc.ClientConn
}

func NewKLAServiceClient(cc *grpc.ClientConn) KLAServiceClient {
	return &kLAServiceClient{cc}
}

func (c *kLAServiceClient) CreateSessionDetail(ctx context.Context, in *CreateSessionDetailRequest, opts ...grpc.CallOption) (*CreateSessionDetailResponse, error) {
	out := new(CreateSessionDetailResponse)
	err := c.cc.Invoke(ctx, "/com.grpc.proto.v0.KLAService/CreateSessionDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kLAServiceClient) GetSessionDetails(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (KLAService_GetSessionDetailsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_KLAService_serviceDesc.Streams[0], "/com.grpc.proto.v0.KLAService/GetSessionDetails", opts...)
	if err != nil {
		return nil, err
	}
	x := &kLAServiceGetSessionDetailsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type KLAService_GetSessionDetailsClient interface {
	Recv() (*CreateSessionDetailRequest, error)
	grpc.ClientStream
}

type kLAServiceGetSessionDetailsClient struct {
	grpc.ClientStream
}

func (x *kLAServiceGetSessionDetailsClient) Recv() (*CreateSessionDetailRequest, error) {
	m := new(CreateSessionDetailRequest)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *kLAServiceClient) CreateSessionInBulk(ctx context.Context, opts ...grpc.CallOption) (KLAService_CreateSessionInBulkClient, error) {
	stream, err := c.cc.NewStream(ctx, &_KLAService_serviceDesc.Streams[1], "/com.grpc.proto.v0.KLAService/CreateSessionInBulk", opts...)
	if err != nil {
		return nil, err
	}
	x := &kLAServiceCreateSessionInBulkClient{stream}
	return x, nil
}

type KLAService_CreateSessionInBulkClient interface {
	Send(*CreateSessionDetailRequest) error
	Recv() (*CreateSessionDetailResponse, error)
	grpc.ClientStream
}

type kLAServiceCreateSessionInBulkClient struct {
	grpc.ClientStream
}

func (x *kLAServiceCreateSessionInBulkClient) Send(m *CreateSessionDetailRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *kLAServiceCreateSessionInBulkClient) Recv() (*CreateSessionDetailResponse, error) {
	m := new(CreateSessionDetailResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// KLAServiceServer is the server API for KLAService service.
type KLAServiceServer interface {
	CreateSessionDetail(context.Context, *CreateSessionDetailRequest) (*CreateSessionDetailResponse, error)
	GetSessionDetails(*empty.Empty, KLAService_GetSessionDetailsServer) error
	CreateSessionInBulk(KLAService_CreateSessionInBulkServer) error
}

// UnimplementedKLAServiceServer can be embedded to have forward compatible implementations.
type UnimplementedKLAServiceServer struct {
}

func (*UnimplementedKLAServiceServer) CreateSessionDetail(ctx context.Context, req *CreateSessionDetailRequest) (*CreateSessionDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSessionDetail not implemented")
}
func (*UnimplementedKLAServiceServer) GetSessionDetails(req *empty.Empty, srv KLAService_GetSessionDetailsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetSessionDetails not implemented")
}
func (*UnimplementedKLAServiceServer) CreateSessionInBulk(srv KLAService_CreateSessionInBulkServer) error {
	return status.Errorf(codes.Unimplemented, "method CreateSessionInBulk not implemented")
}

func RegisterKLAServiceServer(s *grpc.Server, srv KLAServiceServer) {
	s.RegisterService(&_KLAService_serviceDesc, srv)
}

func _KLAService_CreateSessionDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KLAServiceServer).CreateSessionDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.grpc.proto.v0.KLAService/CreateSessionDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KLAServiceServer).CreateSessionDetail(ctx, req.(*CreateSessionDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KLAService_GetSessionDetails_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(empty.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KLAServiceServer).GetSessionDetails(m, &kLAServiceGetSessionDetailsServer{stream})
}

type KLAService_GetSessionDetailsServer interface {
	Send(*CreateSessionDetailRequest) error
	grpc.ServerStream
}

type kLAServiceGetSessionDetailsServer struct {
	grpc.ServerStream
}

func (x *kLAServiceGetSessionDetailsServer) Send(m *CreateSessionDetailRequest) error {
	return x.ServerStream.SendMsg(m)
}

func _KLAService_CreateSessionInBulk_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(KLAServiceServer).CreateSessionInBulk(&kLAServiceCreateSessionInBulkServer{stream})
}

type KLAService_CreateSessionInBulkServer interface {
	Send(*CreateSessionDetailResponse) error
	Recv() (*CreateSessionDetailRequest, error)
	grpc.ServerStream
}

type kLAServiceCreateSessionInBulkServer struct {
	grpc.ServerStream
}

func (x *kLAServiceCreateSessionInBulkServer) Send(m *CreateSessionDetailResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *kLAServiceCreateSessionInBulkServer) Recv() (*CreateSessionDetailRequest, error) {
	m := new(CreateSessionDetailRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _KLAService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "com.grpc.proto.v0.KLAService",
	HandlerType: (*KLAServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSessionDetail",
			Handler:    _KLAService_CreateSessionDetail_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetSessionDetails",
			Handler:       _KLAService_GetSessionDetails_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "CreateSessionInBulk",
			Handler:       _KLAService_CreateSessionInBulk_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "kla.proto",
}
