// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/kla/demo/java/proto/kla.proto

package com.kla.demo.java.dto.v0;

public final class KLAProto {
  private KLAProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CreateSessionDetailRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.grpc.proto.v0.CreateSessionDetailRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional string talk = 2;</code>
     */
    java.lang.String getTalk();
    /**
     * <code>optional string talk = 2;</code>
     */
    com.google.protobuf.ByteString
        getTalkBytes();

    /**
     * <code>optional string abstract = 3;</code>
     */
    java.lang.String getAbstract();
    /**
     * <code>optional string abstract = 3;</code>
     */
    com.google.protobuf.ByteString
        getAbstractBytes();

    /**
     * <code>optional int64 talkTime = 4;</code>
     */
    long getTalkTime();
  }
  /**
   * Protobuf type {@code com.grpc.proto.v0.CreateSessionDetailRequest}
   */
  public  static final class CreateSessionDetailRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.grpc.proto.v0.CreateSessionDetailRequest)
      CreateSessionDetailRequestOrBuilder {
    // Use CreateSessionDetailRequest.newBuilder() to construct.
    private CreateSessionDetailRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CreateSessionDetailRequest() {
      name_ = "";
      talk_ = "";
      abstract_ = "";
      talkTime_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private CreateSessionDetailRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              talk_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              abstract_ = s;
              break;
            }
            case 32: {

              talkTime_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kla.demo.java.dto.v0.KLAProto.internal_static_com_grpc_proto_v0_CreateSessionDetailRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kla.demo.java.dto.v0.KLAProto.internal_static_com_grpc_proto_v0_CreateSessionDetailRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequest.class, com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequest.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TALK_FIELD_NUMBER = 2;
    private volatile java.lang.Object talk_;
    /**
     * <code>optional string talk = 2;</code>
     */
    public java.lang.String getTalk() {
      java.lang.Object ref = talk_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        talk_ = s;
        return s;
      }
    }
    /**
     * <code>optional string talk = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTalkBytes() {
      java.lang.Object ref = talk_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        talk_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ABSTRACT_FIELD_NUMBER = 3;
    private volatile java.lang.Object abstract_;
    /**
     * <code>optional string abstract = 3;</code>
     */
    public java.lang.String getAbstract() {
      java.lang.Object ref = abstract_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        abstract_ = s;
        return s;
      }
    }
    /**
     * <code>optional string abstract = 3;</code>
     */
    public com.google.protobuf.ByteString
        getAbstractBytes() {
      java.lang.Object ref = abstract_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        abstract_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TALKTIME_FIELD_NUMBER = 4;
    private long talkTime_;
    /**
     * <code>optional int64 talkTime = 4;</code>
     */
    public long getTalkTime() {
      return talkTime_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (!getTalkBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, talk_);
      }
      if (!getAbstractBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, abstract_);
      }
      if (talkTime_ != 0L) {
        output.writeInt64(4, talkTime_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (!getTalkBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, talk_);
      }
      if (!getAbstractBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, abstract_);
      }
      if (talkTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, talkTime_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequest)) {
        return super.equals(obj);
      }
      com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequest other = (com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequest) obj;

      boolean result = true;
      result = result && getName()
          .equals(other.getName());
      result = result && getTalk()
          .equals(other.getTalk());
      result = result && getAbstract()
          .equals(other.getAbstract());
      result = result && (getTalkTime()
          == other.getTalkTime());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + TALK_FIELD_NUMBER;
      hash = (53 * hash) + getTalk().hashCode();
      hash = (37 * hash) + ABSTRACT_FIELD_NUMBER;
      hash = (53 * hash) + getAbstract().hashCode();
      hash = (37 * hash) + TALKTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTalkTime());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.grpc.proto.v0.CreateSessionDetailRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.grpc.proto.v0.CreateSessionDetailRequest)
        com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.kla.demo.java.dto.v0.KLAProto.internal_static_com_grpc_proto_v0_CreateSessionDetailRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.kla.demo.java.dto.v0.KLAProto.internal_static_com_grpc_proto_v0_CreateSessionDetailRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequest.class, com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequest.Builder.class);
      }

      // Construct using com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";

        talk_ = "";

        abstract_ = "";

        talkTime_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.kla.demo.java.dto.v0.KLAProto.internal_static_com_grpc_proto_v0_CreateSessionDetailRequest_descriptor;
      }

      public com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequest getDefaultInstanceForType() {
        return com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequest.getDefaultInstance();
      }

      public com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequest build() {
        com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequest buildPartial() {
        com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequest result = new com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequest(this);
        result.name_ = name_;
        result.talk_ = talk_;
        result.abstract_ = abstract_;
        result.talkTime_ = talkTime_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequest) {
          return mergeFrom((com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequest other) {
        if (other == com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequest.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getTalk().isEmpty()) {
          talk_ = other.talk_;
          onChanged();
        }
        if (!other.getAbstract().isEmpty()) {
          abstract_ = other.abstract_;
          onChanged();
        }
        if (other.getTalkTime() != 0L) {
          setTalkTime(other.getTalkTime());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object talk_ = "";
      /**
       * <code>optional string talk = 2;</code>
       */
      public java.lang.String getTalk() {
        java.lang.Object ref = talk_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          talk_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string talk = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTalkBytes() {
        java.lang.Object ref = talk_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          talk_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string talk = 2;</code>
       */
      public Builder setTalk(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        talk_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string talk = 2;</code>
       */
      public Builder clearTalk() {
        
        talk_ = getDefaultInstance().getTalk();
        onChanged();
        return this;
      }
      /**
       * <code>optional string talk = 2;</code>
       */
      public Builder setTalkBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        talk_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object abstract_ = "";
      /**
       * <code>optional string abstract = 3;</code>
       */
      public java.lang.String getAbstract() {
        java.lang.Object ref = abstract_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          abstract_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string abstract = 3;</code>
       */
      public com.google.protobuf.ByteString
          getAbstractBytes() {
        java.lang.Object ref = abstract_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          abstract_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string abstract = 3;</code>
       */
      public Builder setAbstract(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        abstract_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string abstract = 3;</code>
       */
      public Builder clearAbstract() {
        
        abstract_ = getDefaultInstance().getAbstract();
        onChanged();
        return this;
      }
      /**
       * <code>optional string abstract = 3;</code>
       */
      public Builder setAbstractBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        abstract_ = value;
        onChanged();
        return this;
      }

      private long talkTime_ ;
      /**
       * <code>optional int64 talkTime = 4;</code>
       */
      public long getTalkTime() {
        return talkTime_;
      }
      /**
       * <code>optional int64 talkTime = 4;</code>
       */
      public Builder setTalkTime(long value) {
        
        talkTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 talkTime = 4;</code>
       */
      public Builder clearTalkTime() {
        
        talkTime_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.grpc.proto.v0.CreateSessionDetailRequest)
    }

    // @@protoc_insertion_point(class_scope:com.grpc.proto.v0.CreateSessionDetailRequest)
    private static final com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequest();
    }

    public static com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CreateSessionDetailRequest>
        PARSER = new com.google.protobuf.AbstractParser<CreateSessionDetailRequest>() {
      public CreateSessionDetailRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CreateSessionDetailRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CreateSessionDetailRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CreateSessionDetailRequest> getParserForType() {
      return PARSER;
    }

    public com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CreateSessionDetailResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.grpc.proto.v0.CreateSessionDetailResponse)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code com.grpc.proto.v0.CreateSessionDetailResponse}
   */
  public  static final class CreateSessionDetailResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.grpc.proto.v0.CreateSessionDetailResponse)
      CreateSessionDetailResponseOrBuilder {
    // Use CreateSessionDetailResponse.newBuilder() to construct.
    private CreateSessionDetailResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CreateSessionDetailResponse() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private CreateSessionDetailResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kla.demo.java.dto.v0.KLAProto.internal_static_com_grpc_proto_v0_CreateSessionDetailResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kla.demo.java.dto.v0.KLAProto.internal_static_com_grpc_proto_v0_CreateSessionDetailResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailResponse.class, com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailResponse.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailResponse)) {
        return super.equals(obj);
      }
      com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailResponse other = (com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailResponse) obj;

      boolean result = true;
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.grpc.proto.v0.CreateSessionDetailResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.grpc.proto.v0.CreateSessionDetailResponse)
        com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.kla.demo.java.dto.v0.KLAProto.internal_static_com_grpc_proto_v0_CreateSessionDetailResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.kla.demo.java.dto.v0.KLAProto.internal_static_com_grpc_proto_v0_CreateSessionDetailResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailResponse.class, com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailResponse.Builder.class);
      }

      // Construct using com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.kla.demo.java.dto.v0.KLAProto.internal_static_com_grpc_proto_v0_CreateSessionDetailResponse_descriptor;
      }

      public com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailResponse getDefaultInstanceForType() {
        return com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailResponse.getDefaultInstance();
      }

      public com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailResponse build() {
        com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailResponse buildPartial() {
        com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailResponse result = new com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailResponse(this);
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailResponse) {
          return mergeFrom((com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailResponse other) {
        if (other == com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailResponse.getDefaultInstance()) return this;
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.grpc.proto.v0.CreateSessionDetailResponse)
    }

    // @@protoc_insertion_point(class_scope:com.grpc.proto.v0.CreateSessionDetailResponse)
    private static final com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailResponse();
    }

    public static com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CreateSessionDetailResponse>
        PARSER = new com.google.protobuf.AbstractParser<CreateSessionDetailResponse>() {
      public CreateSessionDetailResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CreateSessionDetailResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CreateSessionDetailResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CreateSessionDetailResponse> getParserForType() {
      return PARSER;
    }

    public com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetSessionDetailsRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.grpc.proto.v0.GetSessionDetailsRequest)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code com.grpc.proto.v0.GetSessionDetailsRequest}
   */
  public  static final class GetSessionDetailsRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.grpc.proto.v0.GetSessionDetailsRequest)
      GetSessionDetailsRequestOrBuilder {
    // Use GetSessionDetailsRequest.newBuilder() to construct.
    private GetSessionDetailsRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetSessionDetailsRequest() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GetSessionDetailsRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kla.demo.java.dto.v0.KLAProto.internal_static_com_grpc_proto_v0_GetSessionDetailsRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kla.demo.java.dto.v0.KLAProto.internal_static_com_grpc_proto_v0_GetSessionDetailsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kla.demo.java.dto.v0.KLAProto.GetSessionDetailsRequest.class, com.kla.demo.java.dto.v0.KLAProto.GetSessionDetailsRequest.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.kla.demo.java.dto.v0.KLAProto.GetSessionDetailsRequest)) {
        return super.equals(obj);
      }
      com.kla.demo.java.dto.v0.KLAProto.GetSessionDetailsRequest other = (com.kla.demo.java.dto.v0.KLAProto.GetSessionDetailsRequest) obj;

      boolean result = true;
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.kla.demo.java.dto.v0.KLAProto.GetSessionDetailsRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kla.demo.java.dto.v0.KLAProto.GetSessionDetailsRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kla.demo.java.dto.v0.KLAProto.GetSessionDetailsRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kla.demo.java.dto.v0.KLAProto.GetSessionDetailsRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kla.demo.java.dto.v0.KLAProto.GetSessionDetailsRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kla.demo.java.dto.v0.KLAProto.GetSessionDetailsRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kla.demo.java.dto.v0.KLAProto.GetSessionDetailsRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.kla.demo.java.dto.v0.KLAProto.GetSessionDetailsRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kla.demo.java.dto.v0.KLAProto.GetSessionDetailsRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kla.demo.java.dto.v0.KLAProto.GetSessionDetailsRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.kla.demo.java.dto.v0.KLAProto.GetSessionDetailsRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.grpc.proto.v0.GetSessionDetailsRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.grpc.proto.v0.GetSessionDetailsRequest)
        com.kla.demo.java.dto.v0.KLAProto.GetSessionDetailsRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.kla.demo.java.dto.v0.KLAProto.internal_static_com_grpc_proto_v0_GetSessionDetailsRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.kla.demo.java.dto.v0.KLAProto.internal_static_com_grpc_proto_v0_GetSessionDetailsRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.kla.demo.java.dto.v0.KLAProto.GetSessionDetailsRequest.class, com.kla.demo.java.dto.v0.KLAProto.GetSessionDetailsRequest.Builder.class);
      }

      // Construct using com.kla.demo.java.dto.v0.KLAProto.GetSessionDetailsRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.kla.demo.java.dto.v0.KLAProto.internal_static_com_grpc_proto_v0_GetSessionDetailsRequest_descriptor;
      }

      public com.kla.demo.java.dto.v0.KLAProto.GetSessionDetailsRequest getDefaultInstanceForType() {
        return com.kla.demo.java.dto.v0.KLAProto.GetSessionDetailsRequest.getDefaultInstance();
      }

      public com.kla.demo.java.dto.v0.KLAProto.GetSessionDetailsRequest build() {
        com.kla.demo.java.dto.v0.KLAProto.GetSessionDetailsRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.kla.demo.java.dto.v0.KLAProto.GetSessionDetailsRequest buildPartial() {
        com.kla.demo.java.dto.v0.KLAProto.GetSessionDetailsRequest result = new com.kla.demo.java.dto.v0.KLAProto.GetSessionDetailsRequest(this);
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kla.demo.java.dto.v0.KLAProto.GetSessionDetailsRequest) {
          return mergeFrom((com.kla.demo.java.dto.v0.KLAProto.GetSessionDetailsRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.kla.demo.java.dto.v0.KLAProto.GetSessionDetailsRequest other) {
        if (other == com.kla.demo.java.dto.v0.KLAProto.GetSessionDetailsRequest.getDefaultInstance()) return this;
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.kla.demo.java.dto.v0.KLAProto.GetSessionDetailsRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.kla.demo.java.dto.v0.KLAProto.GetSessionDetailsRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.grpc.proto.v0.GetSessionDetailsRequest)
    }

    // @@protoc_insertion_point(class_scope:com.grpc.proto.v0.GetSessionDetailsRequest)
    private static final com.kla.demo.java.dto.v0.KLAProto.GetSessionDetailsRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.kla.demo.java.dto.v0.KLAProto.GetSessionDetailsRequest();
    }

    public static com.kla.demo.java.dto.v0.KLAProto.GetSessionDetailsRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetSessionDetailsRequest>
        PARSER = new com.google.protobuf.AbstractParser<GetSessionDetailsRequest>() {
      public GetSessionDetailsRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GetSessionDetailsRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetSessionDetailsRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetSessionDetailsRequest> getParserForType() {
      return PARSER;
    }

    public com.kla.demo.java.dto.v0.KLAProto.GetSessionDetailsRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetSessionDetailsResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.grpc.proto.v0.GetSessionDetailsResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.grpc.proto.v0.CreateSessionDetailRequest createSessionDetailRequest = 1;</code>
     */
    java.util.List<com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequest> 
        getCreateSessionDetailRequestList();
    /**
     * <code>repeated .com.grpc.proto.v0.CreateSessionDetailRequest createSessionDetailRequest = 1;</code>
     */
    com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequest getCreateSessionDetailRequest(int index);
    /**
     * <code>repeated .com.grpc.proto.v0.CreateSessionDetailRequest createSessionDetailRequest = 1;</code>
     */
    int getCreateSessionDetailRequestCount();
    /**
     * <code>repeated .com.grpc.proto.v0.CreateSessionDetailRequest createSessionDetailRequest = 1;</code>
     */
    java.util.List<? extends com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequestOrBuilder> 
        getCreateSessionDetailRequestOrBuilderList();
    /**
     * <code>repeated .com.grpc.proto.v0.CreateSessionDetailRequest createSessionDetailRequest = 1;</code>
     */
    com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequestOrBuilder getCreateSessionDetailRequestOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.grpc.proto.v0.GetSessionDetailsResponse}
   */
  public  static final class GetSessionDetailsResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.grpc.proto.v0.GetSessionDetailsResponse)
      GetSessionDetailsResponseOrBuilder {
    // Use GetSessionDetailsResponse.newBuilder() to construct.
    private GetSessionDetailsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetSessionDetailsResponse() {
      createSessionDetailRequest_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GetSessionDetailsResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                createSessionDetailRequest_ = new java.util.ArrayList<com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequest>();
                mutable_bitField0_ |= 0x00000001;
              }
              createSessionDetailRequest_.add(
                  input.readMessage(com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequest.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          createSessionDetailRequest_ = java.util.Collections.unmodifiableList(createSessionDetailRequest_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kla.demo.java.dto.v0.KLAProto.internal_static_com_grpc_proto_v0_GetSessionDetailsResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kla.demo.java.dto.v0.KLAProto.internal_static_com_grpc_proto_v0_GetSessionDetailsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kla.demo.java.dto.v0.KLAProto.GetSessionDetailsResponse.class, com.kla.demo.java.dto.v0.KLAProto.GetSessionDetailsResponse.Builder.class);
    }

    public static final int CREATESESSIONDETAILREQUEST_FIELD_NUMBER = 1;
    private java.util.List<com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequest> createSessionDetailRequest_;
    /**
     * <code>repeated .com.grpc.proto.v0.CreateSessionDetailRequest createSessionDetailRequest = 1;</code>
     */
    public java.util.List<com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequest> getCreateSessionDetailRequestList() {
      return createSessionDetailRequest_;
    }
    /**
     * <code>repeated .com.grpc.proto.v0.CreateSessionDetailRequest createSessionDetailRequest = 1;</code>
     */
    public java.util.List<? extends com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequestOrBuilder> 
        getCreateSessionDetailRequestOrBuilderList() {
      return createSessionDetailRequest_;
    }
    /**
     * <code>repeated .com.grpc.proto.v0.CreateSessionDetailRequest createSessionDetailRequest = 1;</code>
     */
    public int getCreateSessionDetailRequestCount() {
      return createSessionDetailRequest_.size();
    }
    /**
     * <code>repeated .com.grpc.proto.v0.CreateSessionDetailRequest createSessionDetailRequest = 1;</code>
     */
    public com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequest getCreateSessionDetailRequest(int index) {
      return createSessionDetailRequest_.get(index);
    }
    /**
     * <code>repeated .com.grpc.proto.v0.CreateSessionDetailRequest createSessionDetailRequest = 1;</code>
     */
    public com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequestOrBuilder getCreateSessionDetailRequestOrBuilder(
        int index) {
      return createSessionDetailRequest_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < createSessionDetailRequest_.size(); i++) {
        output.writeMessage(1, createSessionDetailRequest_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < createSessionDetailRequest_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, createSessionDetailRequest_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.kla.demo.java.dto.v0.KLAProto.GetSessionDetailsResponse)) {
        return super.equals(obj);
      }
      com.kla.demo.java.dto.v0.KLAProto.GetSessionDetailsResponse other = (com.kla.demo.java.dto.v0.KLAProto.GetSessionDetailsResponse) obj;

      boolean result = true;
      result = result && getCreateSessionDetailRequestList()
          .equals(other.getCreateSessionDetailRequestList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getCreateSessionDetailRequestCount() > 0) {
        hash = (37 * hash) + CREATESESSIONDETAILREQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getCreateSessionDetailRequestList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.kla.demo.java.dto.v0.KLAProto.GetSessionDetailsResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kla.demo.java.dto.v0.KLAProto.GetSessionDetailsResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kla.demo.java.dto.v0.KLAProto.GetSessionDetailsResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kla.demo.java.dto.v0.KLAProto.GetSessionDetailsResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kla.demo.java.dto.v0.KLAProto.GetSessionDetailsResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kla.demo.java.dto.v0.KLAProto.GetSessionDetailsResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kla.demo.java.dto.v0.KLAProto.GetSessionDetailsResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.kla.demo.java.dto.v0.KLAProto.GetSessionDetailsResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kla.demo.java.dto.v0.KLAProto.GetSessionDetailsResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kla.demo.java.dto.v0.KLAProto.GetSessionDetailsResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.kla.demo.java.dto.v0.KLAProto.GetSessionDetailsResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.grpc.proto.v0.GetSessionDetailsResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.grpc.proto.v0.GetSessionDetailsResponse)
        com.kla.demo.java.dto.v0.KLAProto.GetSessionDetailsResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.kla.demo.java.dto.v0.KLAProto.internal_static_com_grpc_proto_v0_GetSessionDetailsResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.kla.demo.java.dto.v0.KLAProto.internal_static_com_grpc_proto_v0_GetSessionDetailsResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.kla.demo.java.dto.v0.KLAProto.GetSessionDetailsResponse.class, com.kla.demo.java.dto.v0.KLAProto.GetSessionDetailsResponse.Builder.class);
      }

      // Construct using com.kla.demo.java.dto.v0.KLAProto.GetSessionDetailsResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getCreateSessionDetailRequestFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (createSessionDetailRequestBuilder_ == null) {
          createSessionDetailRequest_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          createSessionDetailRequestBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.kla.demo.java.dto.v0.KLAProto.internal_static_com_grpc_proto_v0_GetSessionDetailsResponse_descriptor;
      }

      public com.kla.demo.java.dto.v0.KLAProto.GetSessionDetailsResponse getDefaultInstanceForType() {
        return com.kla.demo.java.dto.v0.KLAProto.GetSessionDetailsResponse.getDefaultInstance();
      }

      public com.kla.demo.java.dto.v0.KLAProto.GetSessionDetailsResponse build() {
        com.kla.demo.java.dto.v0.KLAProto.GetSessionDetailsResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.kla.demo.java.dto.v0.KLAProto.GetSessionDetailsResponse buildPartial() {
        com.kla.demo.java.dto.v0.KLAProto.GetSessionDetailsResponse result = new com.kla.demo.java.dto.v0.KLAProto.GetSessionDetailsResponse(this);
        int from_bitField0_ = bitField0_;
        if (createSessionDetailRequestBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            createSessionDetailRequest_ = java.util.Collections.unmodifiableList(createSessionDetailRequest_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.createSessionDetailRequest_ = createSessionDetailRequest_;
        } else {
          result.createSessionDetailRequest_ = createSessionDetailRequestBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kla.demo.java.dto.v0.KLAProto.GetSessionDetailsResponse) {
          return mergeFrom((com.kla.demo.java.dto.v0.KLAProto.GetSessionDetailsResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.kla.demo.java.dto.v0.KLAProto.GetSessionDetailsResponse other) {
        if (other == com.kla.demo.java.dto.v0.KLAProto.GetSessionDetailsResponse.getDefaultInstance()) return this;
        if (createSessionDetailRequestBuilder_ == null) {
          if (!other.createSessionDetailRequest_.isEmpty()) {
            if (createSessionDetailRequest_.isEmpty()) {
              createSessionDetailRequest_ = other.createSessionDetailRequest_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureCreateSessionDetailRequestIsMutable();
              createSessionDetailRequest_.addAll(other.createSessionDetailRequest_);
            }
            onChanged();
          }
        } else {
          if (!other.createSessionDetailRequest_.isEmpty()) {
            if (createSessionDetailRequestBuilder_.isEmpty()) {
              createSessionDetailRequestBuilder_.dispose();
              createSessionDetailRequestBuilder_ = null;
              createSessionDetailRequest_ = other.createSessionDetailRequest_;
              bitField0_ = (bitField0_ & ~0x00000001);
              createSessionDetailRequestBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getCreateSessionDetailRequestFieldBuilder() : null;
            } else {
              createSessionDetailRequestBuilder_.addAllMessages(other.createSessionDetailRequest_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.kla.demo.java.dto.v0.KLAProto.GetSessionDetailsResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.kla.demo.java.dto.v0.KLAProto.GetSessionDetailsResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequest> createSessionDetailRequest_ =
        java.util.Collections.emptyList();
      private void ensureCreateSessionDetailRequestIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          createSessionDetailRequest_ = new java.util.ArrayList<com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequest>(createSessionDetailRequest_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequest, com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequest.Builder, com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequestOrBuilder> createSessionDetailRequestBuilder_;

      /**
       * <code>repeated .com.grpc.proto.v0.CreateSessionDetailRequest createSessionDetailRequest = 1;</code>
       */
      public java.util.List<com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequest> getCreateSessionDetailRequestList() {
        if (createSessionDetailRequestBuilder_ == null) {
          return java.util.Collections.unmodifiableList(createSessionDetailRequest_);
        } else {
          return createSessionDetailRequestBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.grpc.proto.v0.CreateSessionDetailRequest createSessionDetailRequest = 1;</code>
       */
      public int getCreateSessionDetailRequestCount() {
        if (createSessionDetailRequestBuilder_ == null) {
          return createSessionDetailRequest_.size();
        } else {
          return createSessionDetailRequestBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.grpc.proto.v0.CreateSessionDetailRequest createSessionDetailRequest = 1;</code>
       */
      public com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequest getCreateSessionDetailRequest(int index) {
        if (createSessionDetailRequestBuilder_ == null) {
          return createSessionDetailRequest_.get(index);
        } else {
          return createSessionDetailRequestBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.grpc.proto.v0.CreateSessionDetailRequest createSessionDetailRequest = 1;</code>
       */
      public Builder setCreateSessionDetailRequest(
          int index, com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequest value) {
        if (createSessionDetailRequestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCreateSessionDetailRequestIsMutable();
          createSessionDetailRequest_.set(index, value);
          onChanged();
        } else {
          createSessionDetailRequestBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.grpc.proto.v0.CreateSessionDetailRequest createSessionDetailRequest = 1;</code>
       */
      public Builder setCreateSessionDetailRequest(
          int index, com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequest.Builder builderForValue) {
        if (createSessionDetailRequestBuilder_ == null) {
          ensureCreateSessionDetailRequestIsMutable();
          createSessionDetailRequest_.set(index, builderForValue.build());
          onChanged();
        } else {
          createSessionDetailRequestBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.grpc.proto.v0.CreateSessionDetailRequest createSessionDetailRequest = 1;</code>
       */
      public Builder addCreateSessionDetailRequest(com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequest value) {
        if (createSessionDetailRequestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCreateSessionDetailRequestIsMutable();
          createSessionDetailRequest_.add(value);
          onChanged();
        } else {
          createSessionDetailRequestBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.grpc.proto.v0.CreateSessionDetailRequest createSessionDetailRequest = 1;</code>
       */
      public Builder addCreateSessionDetailRequest(
          int index, com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequest value) {
        if (createSessionDetailRequestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCreateSessionDetailRequestIsMutable();
          createSessionDetailRequest_.add(index, value);
          onChanged();
        } else {
          createSessionDetailRequestBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.grpc.proto.v0.CreateSessionDetailRequest createSessionDetailRequest = 1;</code>
       */
      public Builder addCreateSessionDetailRequest(
          com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequest.Builder builderForValue) {
        if (createSessionDetailRequestBuilder_ == null) {
          ensureCreateSessionDetailRequestIsMutable();
          createSessionDetailRequest_.add(builderForValue.build());
          onChanged();
        } else {
          createSessionDetailRequestBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.grpc.proto.v0.CreateSessionDetailRequest createSessionDetailRequest = 1;</code>
       */
      public Builder addCreateSessionDetailRequest(
          int index, com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequest.Builder builderForValue) {
        if (createSessionDetailRequestBuilder_ == null) {
          ensureCreateSessionDetailRequestIsMutable();
          createSessionDetailRequest_.add(index, builderForValue.build());
          onChanged();
        } else {
          createSessionDetailRequestBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.grpc.proto.v0.CreateSessionDetailRequest createSessionDetailRequest = 1;</code>
       */
      public Builder addAllCreateSessionDetailRequest(
          java.lang.Iterable<? extends com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequest> values) {
        if (createSessionDetailRequestBuilder_ == null) {
          ensureCreateSessionDetailRequestIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, createSessionDetailRequest_);
          onChanged();
        } else {
          createSessionDetailRequestBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.grpc.proto.v0.CreateSessionDetailRequest createSessionDetailRequest = 1;</code>
       */
      public Builder clearCreateSessionDetailRequest() {
        if (createSessionDetailRequestBuilder_ == null) {
          createSessionDetailRequest_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          createSessionDetailRequestBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.grpc.proto.v0.CreateSessionDetailRequest createSessionDetailRequest = 1;</code>
       */
      public Builder removeCreateSessionDetailRequest(int index) {
        if (createSessionDetailRequestBuilder_ == null) {
          ensureCreateSessionDetailRequestIsMutable();
          createSessionDetailRequest_.remove(index);
          onChanged();
        } else {
          createSessionDetailRequestBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.grpc.proto.v0.CreateSessionDetailRequest createSessionDetailRequest = 1;</code>
       */
      public com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequest.Builder getCreateSessionDetailRequestBuilder(
          int index) {
        return getCreateSessionDetailRequestFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.grpc.proto.v0.CreateSessionDetailRequest createSessionDetailRequest = 1;</code>
       */
      public com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequestOrBuilder getCreateSessionDetailRequestOrBuilder(
          int index) {
        if (createSessionDetailRequestBuilder_ == null) {
          return createSessionDetailRequest_.get(index);  } else {
          return createSessionDetailRequestBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.grpc.proto.v0.CreateSessionDetailRequest createSessionDetailRequest = 1;</code>
       */
      public java.util.List<? extends com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequestOrBuilder> 
           getCreateSessionDetailRequestOrBuilderList() {
        if (createSessionDetailRequestBuilder_ != null) {
          return createSessionDetailRequestBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(createSessionDetailRequest_);
        }
      }
      /**
       * <code>repeated .com.grpc.proto.v0.CreateSessionDetailRequest createSessionDetailRequest = 1;</code>
       */
      public com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequest.Builder addCreateSessionDetailRequestBuilder() {
        return getCreateSessionDetailRequestFieldBuilder().addBuilder(
            com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequest.getDefaultInstance());
      }
      /**
       * <code>repeated .com.grpc.proto.v0.CreateSessionDetailRequest createSessionDetailRequest = 1;</code>
       */
      public com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequest.Builder addCreateSessionDetailRequestBuilder(
          int index) {
        return getCreateSessionDetailRequestFieldBuilder().addBuilder(
            index, com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequest.getDefaultInstance());
      }
      /**
       * <code>repeated .com.grpc.proto.v0.CreateSessionDetailRequest createSessionDetailRequest = 1;</code>
       */
      public java.util.List<com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequest.Builder> 
           getCreateSessionDetailRequestBuilderList() {
        return getCreateSessionDetailRequestFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequest, com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequest.Builder, com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequestOrBuilder> 
          getCreateSessionDetailRequestFieldBuilder() {
        if (createSessionDetailRequestBuilder_ == null) {
          createSessionDetailRequestBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequest, com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequest.Builder, com.kla.demo.java.dto.v0.KLAProto.CreateSessionDetailRequestOrBuilder>(
                  createSessionDetailRequest_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          createSessionDetailRequest_ = null;
        }
        return createSessionDetailRequestBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.grpc.proto.v0.GetSessionDetailsResponse)
    }

    // @@protoc_insertion_point(class_scope:com.grpc.proto.v0.GetSessionDetailsResponse)
    private static final com.kla.demo.java.dto.v0.KLAProto.GetSessionDetailsResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.kla.demo.java.dto.v0.KLAProto.GetSessionDetailsResponse();
    }

    public static com.kla.demo.java.dto.v0.KLAProto.GetSessionDetailsResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetSessionDetailsResponse>
        PARSER = new com.google.protobuf.AbstractParser<GetSessionDetailsResponse>() {
      public GetSessionDetailsResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GetSessionDetailsResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetSessionDetailsResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetSessionDetailsResponse> getParserForType() {
      return PARSER;
    }

    public com.kla.demo.java.dto.v0.KLAProto.GetSessionDetailsResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpc_proto_v0_CreateSessionDetailRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_grpc_proto_v0_CreateSessionDetailRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpc_proto_v0_CreateSessionDetailResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_grpc_proto_v0_CreateSessionDetailResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpc_proto_v0_GetSessionDetailsRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_grpc_proto_v0_GetSessionDetailsRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpc_proto_v0_GetSessionDetailsResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_grpc_proto_v0_GetSessionDetailsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!com/kla/demo/java/proto/kla.proto\022\021com" +
      ".grpc.proto.v0\032\033google/protobuf/empty.pr" +
      "oto\"\\\n\032CreateSessionDetailRequest\022\014\n\004nam" +
      "e\030\001 \001(\t\022\014\n\004talk\030\002 \001(\t\022\020\n\010abstract\030\003 \001(\t\022" +
      "\020\n\010talkTime\030\004 \001(\003\"\035\n\033CreateSessionDetail" +
      "Response\"\032\n\030GetSessionDetailsRequest\"n\n\031" +
      "GetSessionDetailsResponse\022Q\n\032createSessi" +
      "onDetailRequest\030\001 \003(\0132-.com.grpc.proto.v" +
      "0.CreateSessionDetailRequest2\332\002\n\nKLAServ" +
      "ice\022t\n\023CreateSessionDetail\022-.com.grpc.pr",
      "oto.v0.CreateSessionDetailRequest\032..com." +
      "grpc.proto.v0.CreateSessionDetailRespons" +
      "e\022\\\n\021GetSessionDetails\022\026.google.protobuf" +
      ".Empty\032-.com.grpc.proto.v0.CreateSession" +
      "DetailRequest0\001\022x\n\023CreateSessionInBulk\022-" +
      ".com.grpc.proto.v0.CreateSessionDetailRe" +
      "quest\032..com.grpc.proto.v0.CreateSessionD" +
      "etailResponse(\0010\001B$\n\030com.kla.demo.java.d" +
      "to.v0B\010KLAProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        }, assigner);
    internal_static_com_grpc_proto_v0_CreateSessionDetailRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_grpc_proto_v0_CreateSessionDetailRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_grpc_proto_v0_CreateSessionDetailRequest_descriptor,
        new java.lang.String[] { "Name", "Talk", "Abstract", "TalkTime", });
    internal_static_com_grpc_proto_v0_CreateSessionDetailResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_grpc_proto_v0_CreateSessionDetailResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_grpc_proto_v0_CreateSessionDetailResponse_descriptor,
        new java.lang.String[] { });
    internal_static_com_grpc_proto_v0_GetSessionDetailsRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_grpc_proto_v0_GetSessionDetailsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_grpc_proto_v0_GetSessionDetailsRequest_descriptor,
        new java.lang.String[] { });
    internal_static_com_grpc_proto_v0_GetSessionDetailsResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_grpc_proto_v0_GetSessionDetailsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_grpc_proto_v0_GetSessionDetailsResponse_descriptor,
        new java.lang.String[] { "CreateSessionDetailRequest", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
